### ISSUE TITLE
Driver supplying packets smaller than `max_pkt_size` triggers assertion

### ISSUE THREAD

**Issue by KireinaHoro** [spcl/pspin#10]
The assertion looks like the following:

```
sim_slp_l1: src/NICInbound.hpp:475: void PsPIN::NICInbound<AXIPortType>::feedback_progress() [with AXIPortType = PsPIN::AXIPort<unsigned int, long unsigned int>]: Assertion `*ni_ctrl.feedback_her_size_i == pktentry.size' failed.
```

I'm currently on commit cf70804b8d63d34a57e86a52f1608c6ba6ba8102.

This happens if the `fill_packet` function does not return `max_pkt_size` (even if just off by one i.e. `max_pkt_size-1`).  I'm pretty sure I'm not overflowing the packet buffer.

**Comment by SalvatoreDiGirolamo** [comment]
Hey, thanks for reporting the issue! 

The problem is that we have two sizes for each packet: 
 - the full packet size (```pkt_size```)
 - and the size indicating the portion of the packet that is needed into L1 (```xfer_size```, ```xfer_size <= pkt_size```). 

Now, the NIC inbound engine expects that the feedback carries the ```pkt_size``` as this can be used to free space into the packet buffer. However, the HPUs are incorrectly building feedbacks that carry the ```xfer_size```, so that assert fails.

We will need to extend the task descriptor to make it carry both sizes, allowing HPUs to build the correct feedback. 

In the meantime, you can safely comment out that assertion as a workaround.

**Comment by KireinaHoro** [comment]
> Hey, thanks for reporting the issue!
> 
> The problem is that we have two sizes for each packet:
> 
> * the full packet size (`pkt_size`)
> * and the size indicating the portion of the packet that is needed into L1 (`xfer_size`, `xfer_size <= pkt_size`).
> 
> Now, the NIC inbound engine expects that the feedback carries the `pkt_size` as this can be used to free space into the packet buffer. However, the HPUs are incorrectly building feedbacks that carry the `xfer_size`, so that assert fails.

I'm still a bit confused, because per this, if the incoming packet is small (e.g. smaller than L1 size), `xfer_size` should be equal to `pkt_size`?  Or is `xfer_size` always fixed to the L1 size regardless of the actual packet (fragment) size?

> 
> We will need to extend the task descriptor to make it carry both sizes, allowing HPUs to build the correct feedback.
> 
> In the meantime, you can safely comment out that assertion as a workaround.

Cool, I'll give this a shot.

**Comment by SalvatoreDiGirolamo** [comment]
> I'm still a bit confused, because per this, if the incoming packet is small (e.g. smaller than L1 size), xfer_size should be equal to pkt_size? Or is xfer_size always fixed to the L1 size regardless of the actual packet (fragment) size?

```xfer_size``` is not directly linked to L1 size. In the application interface, you are supposed to specify in the execution context how much of a packet you want into L1 for fast access. Then, all packets matching that execution context will have that much of their payload moved transparently to L1 before the handlers gets called. 

In the simulation driver interface, you can specify this on a per-packet basis: [here](https://github.com/spcl/pspin/blob/master/hw/verilator_model/include/pspinsim.h#L73) (```pkt_l1_len``` parameter).
